// config/restaurante.js
// =============================================
// CONFIGURACIÓN COMPLETA DE MR. SUSHI
// 25 sucursales reales + menú completo
// Promociones actualizadas: junio 2026
// =============================================

module.exports = {
  nombre: "Mr. Sushi",
  telefono_principal: "33 9427 2277",

  horario_general: {
    lunes:     { abre: "12:00", cierra: "22:00" },
    martes:    { abre: "12:00", cierra: "22:00" },
    miercoles: { abre: "12:00", cierra: "22:00" },
    jueves:    { abre: "12:00", cierra: "22:00" },
    viernes:   { abre: "12:00", cierra: "22:00" },
    sabado:    { abre: "12:00", cierra: "22:00" },
    domingo:   { abre: "13:00", cierra: "21:00" },
  },

  // ============================================================
  // PROMOCIONES ACTIVAS 2026
  // Fuente: PDF "Promociones Activas 2026"
  // ============================================================
  promociones_generales: [
    {
      nombre: "Barra Libre de Sushi",
      descripcion: "Come sushi ilimitado por $297 por persona.",
      precio: 297,
      dias: ["miercoles", "jueves", "viernes", "sabado"],
      hora_inicio: "18:00",
      hora_fin: "22:30",
      vigencia: "hasta_nuevo_aviso",
      aplica_a: "restaurante",
      notas: "Solo en restaurante/híbrido. NO aplica en Fast Food ni delivery.",
    },
    {
      nombre: "Coctelería 2x1",
      descripcion: "Pide 2 cócteles y paga solo 1.",
      precio: null,
      dias: ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"],
      hora_inicio: "13:00",
      hora_fin: "22:30",
      hora_fin_domingo: "22:00",
      vigencia: "hasta_nuevo_aviso",
      aplica_a: "restaurante",
      notas: "Lun–Sáb hasta 22:30, Dom hasta 22:00. Solo en restaurante/híbrido. NO aplica en Fast Food.",
    },
    {
      nombre: "Lunch Box",
      descripcion: "Elige 1 entrada + 1 arroz + 1 rollo + 1 agua por $197. Solo 1 alimento por categoría, extras se cobran aparte.",
      precio: 197,
      dias: ["lunes", "martes", "miercoles", "jueves"],
      hora_inicio: "12:00",
      hora_fin: "22:00",
      vigencia: "hasta_nuevo_aviso",
      aplica_a: "todos",
      notas: "Lun–Jue todo el día. Aplica en restaurante y Fast Food.",
      opciones: {
        entrada: ["Edamames Asados", "Kushiague de Queso (1 pza)", "Kushiague de Plátano/Queso (1 pza)"],
        arroz:   ["Yakimeshi Verduras", "Gohan Clásico"],
        rollo:   ["Tuna King", "Spicy Tuna", "Mr. Fura", "Tampico Maki Especial", "Mr. Manchego", "Mr. Kakiague", "Tempura Maki", "Tunagui", "Filadelfia Atún", "Filadelfia Cangrejo", "Filadelfia Camarón", "California Atún", "California Cangrejo", "California Camarón", "Avocado Maki Atún", "Avocado Maki Cangrejo", "Avocado Maki Camarón"],
        agua:    ["Agua Maracuyá/Mango", "Agua Pepino con Limón"],
      },
    },
    {
      nombre: "Mr. 4x4",
      descripcion: "Elige 4 medios rollos. $217 todos los días, $199 solo los martes.",
      precio_normal: 217,
      precio_martes: 199,
      dias: ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"],
      hora_inicio: "12:00",
      hora_fin: "22:00",
      vigencia: "hasta_nuevo_aviso",
      aplica_a: "todos",
      notas: "Todos los días en restaurante y Fast Food. Los martes precio especial $199.",
    },
  ],

  sucursales: [
    { id:1,  nombre:"Americana",            tipo:"restaurante", zona:"CDMX",   direccion:"Col. Americana, Cto. Américas No. 2031", telefono:"55 5378 0625", telefono_transferencia:"55 5378 0625", whatsapp:"+52 55 5378 0625", horario_propio:null, promociones_propias:[] },
    { id:2,  nombre:"Arboledas",            tipo:"restaurante", zona:"EDOMEX", direccion:"Fracc. Las Arboledas, Av. Jiménez No. 60 Locales 3 y 7, Tlalnepantla, Edo. De Méx. 54028", telefono:"55 5370 7647", telefono_transferencia:"55 5370 7647", whatsapp:"+52 55 5370 7647", horario_propio:null, promociones_propias:[] },
    { id:3,  nombre:"Atizapán",             tipo:"fast_food",   zona:"EDOMEX", direccion:"Fracc. Lomas de Atizapán, Av. Ruiz Cortínez No. 295 Local 365, Atizapán de Z., Edo. de Méx. 52977", telefono:"55 1669 9047 / 55 1669 9198", telefono_transferencia:"55 1669 9047", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:4,  nombre:"Call Center",          tipo:"fast_food",   zona:"EDOMEX", direccion:"Atizapán de Z., Edo. de Méx. 52977", telefono:"55 6291 5401", telefono_transferencia:"55 6291 5401", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:5,  nombre:"Fuentes de Satélite",  tipo:"restaurante", zona:"EDOMEX", direccion:"Col. Jardines de Satélite, No. 1 Locales 8-10, Tlalnepantla, Edo. De Méx.", telefono:"55 5572 8868 / 55 5572 8889 / 55 5572 7219", telefono_transferencia:"55 5572 8868", whatsapp:"+52 55 5572 8868", horario_propio:null, promociones_propias:[] },
    { id:6,  nombre:"Centro Santa Fe",      tipo:"fast_food",   zona:"CDMX",   direccion:"Col. Antigua Mina La Trinidad, Col. Vasco de Quiroga No. 3800 L-715, Álvaro Obregón, CDMX 01210", telefono:"55 2167 8563", telefono_transferencia:"55 2167 8563", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:7,  nombre:"Coapa",                tipo:"fast_food",   zona:"CDMX",   direccion:"Calle. Del Hueso No. 519 L-417, Coyoacán, CDMX", telefono:"55 1741 6734", telefono_transferencia:"55 1741 6734", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:8,  nombre:"Cuernavaca",           tipo:"fast_food",   zona:"MOR",    direccion:"Km. 87.5 Autopista Méx.-Acap. L-208, Col. Galerías Cuernavaca, Col. Flores Magón, Cuernavaca, Mor.", telefono:"777 315 9917", telefono_transferencia:"777 315 9917", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:9,  nombre:"Delta",                tipo:"fast_food",   zona:"EDOMEX", direccion:"Col. Residencial Acoxpa, Alcaldía Tlalpan, CDMX", telefono:"55 1741 6734", telefono_transferencia:"55 1741 6734", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:10, nombre:"Hahha Azul",           tipo:"restaurante", zona:"EDOMEX", direccion:"Cto. Circumvalación Poniente 16 L-R, Ciudad Satélite Zona Azul, Naucalpan, Méx. 53100", telefono:"55 5393 0232 / 55 5572 3088", telefono_transferencia:"55 5393 0232", whatsapp:"+52 55 5393 0232", horario_propio:null, promociones_propias:[] },
    { id:11, nombre:"Hahha Esmeralda",      tipo:"restaurante", zona:"EDOMEX", direccion:"Col. Fracc. Bosque Esmeralda, Atizapán de Z., Edo. De Méx. 52930", telefono:"55 5572 2086", telefono_transferencia:"55 5572 2086", whatsapp:"+52 55 5572 2086", horario_propio:null, promociones_propias:[] },
    { id:12, nombre:"Lomas Verdes",         tipo:"fast_food",   zona:"EDOMEX", direccion:"Col. Colinas de la Gran Torre, Atizapán de Zaragoza, Edo. Méx. 52920", telefono:"55 1443 0136 / 55 5393 3000", telefono_transferencia:"55 1443 0136", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:13, nombre:"Masaryk",              tipo:"restaurante", zona:"CDMX",   direccion:"Col. Polanco, Alcaldía Miguel Hidalgo, 11560, CDMX", telefono:"55 5280 5481 / 55 5280 7614", telefono_transferencia:"55 5280 5481", whatsapp:"+52 55 5280 5481", horario_propio:null, promociones_propias:[] },
    { id:14, nombre:"Galerías Metepec",     tipo:"restaurante", zona:"EDOMEX", direccion:"Blvd. Manuel Ávila Camacho # 1007, Centro Comercial 'Mundo E', Metepec, Estado de México 52102", telefono:"722 232 6836 / 722 232 0464", telefono_transferencia:"722 232 6836", whatsapp:"+52 722 232 6836", horario_propio:null, promociones_propias:[] },
    { id:15, nombre:"Mundo E",              tipo:"restaurante", zona:"EDOMEX", direccion:"Col. San Lucas Tepetlacalco, Tlalnepantla, Edo. De México 54095", telefono:"55 9105 2073 / 55 9105 2012", telefono_transferencia:"55 9105 2073", whatsapp:"+52 55 9105 2073", horario_propio:null, promociones_propias:[] },
    { id:16, nombre:"Patriotismo",          tipo:"restaurante", zona:"CDMX",   direccion:"Av. Patriotismo No. 229 Local R-03, Col. San Pedro de Los Pinos, CDMX", telefono:"55 5271 8286 / 55 5271 8158", telefono_transferencia:"55 5271 8286", whatsapp:"+52 55 5271 8286", horario_propio:null, promociones_propias:[] },
    { id:17, nombre:"Perisur",              tipo:"fast_food",   zona:"CDMX",   direccion:"C.C. Metrópoli Patriotismo, Alcaldía Benito Juárez, Col. Narvarte Poniente, Local RA-10 y RA-10B Tercer Piso, CDMX", telefono:"55 5035 5989 / 55 6035 5984", telefono_transferencia:"55 5035 5989", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:18, nombre:"Galerías Serdán",      tipo:"restaurante", zona:"PUE",    direccion:"Puebla, Pue. 72000, Col. Rancho Hermoso, Galerías Serdán, Col. Hermanos Serdán a 170 L-129", telefono:"222 622 4266 / 222 290 4481", telefono_transferencia:"222 622 4266", whatsapp:"+52 222 622 4266", horario_propio:null, promociones_propias:[] },
    { id:19, nombre:"Zona Azul Restaurante",tipo:"fast_food",   zona:"EDOMEX", direccion:"Circuito Circumvalación Poniente 16, Ciudad Satélite Zona Azul, Naucalpan 53100, Local S", telefono:"55 5572 9809 / 55 5572 3087", telefono_transferencia:"55 5572 9809", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:20, nombre:"Satélite Anexo",       tipo:"fast_food",   zona:"EDOMEX", direccion:"Av. De Las Fuentes No. 28, Col. Tecamachalco, Edo. De México 53100, Local N", telefono:"55 5572 3336 / 55 5572 9809", telefono_transferencia:"55 5572 3336", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:21, nombre:"Tecamachalco",         tipo:"restaurante", zona:"EDOMEX", direccion:"Centro Comercial 'Galerías Toluca', Paseo Tollocan Esa. 11 De Mayo, Col. Santa Ana Tlapaltitlan", telefono:"55 5253 0194 / 55 5569 2653 / 55 5569 0469", telefono_transferencia:"55 5253 0194", whatsapp:"+52 55 5253 0194", horario_propio:null, promociones_propias:[] },
    { id:22, nombre:"Galerías Toluca",      tipo:"fast_food",   zona:"EDOMEX", direccion:"Dulce, Edo. De México 50140, Centro Comercial, Galerías Toluca", telefono:"33 1655 1487", telefono_transferencia:"33 1655 1487", whatsapp:null, horario_propio:null, promociones_propias:[] },
    { id:23, nombre:"Urban Center",         tipo:"restaurante", zona:"EDOMEX", direccion:"Av. Adolfo López Sur No. 7000 Local 3, Centro Alta, Centro Comercial Urban Center, Tlalnepantla", telefono:"55 6310 7134", telefono_transferencia:"55 6310 7134", whatsapp:"+52 55 6310 7134", horario_propio:null, promociones_propias:[] },
    { id:24, nombre:"Vallejo",              tipo:"restaurante", zona:"CDMX",   direccion:"Alcaldía Azcapotzalco, Col. Clavería, Calle Talavera 14, Colonia Via Vallejo, CDMX", telefono:"55 5308 2457 / 55 5308 2250 / 55 5308 2206", telefono_transferencia:"55 5308 2457", whatsapp:"+52 55 5308 2457", horario_propio:null, promociones_propias:[] },
    { id:25, nombre:"Zona Esmeralda",       tipo:"restaurante", zona:"EDOMEX", direccion:"Azcapotzalco de Z., Col. Valdecasas Condominio No. 113-A, Atizapán de Z., Edo. De México 52937", telefono:"55 5008 2001", telefono_transferencia:"55 5008 2001", whatsapp:"+52 55 5008 2001", horario_propio:null, promociones_propias:[] },
  ],

  menu: {
    "Sushi 2x1": [
      { nombre:"Sushi Tunagui",              precio:249, descripcion:"Atún, Anguila, Masago y Aguacate." },
      { nombre:"Sushi Tuna King",            precio:269, descripcion:"Atún Picante, Aguacate y Chile Tempura." },
      { nombre:"Sushi Tempura Maki",         precio:249, descripcion:"Queso Crema, Tempura, Cangrejo y Chile." },
      { nombre:"Sushi Mr. Kakiage",          precio:249, descripcion:"Verduras Tempura, Cangrejo y Queso." },
      { nombre:"Sushi Kani Maki",            precio:259, descripcion:"Cangrejo, Queso Crema, Aguacate y Pepino." },
      { nombre:"Sushi Mr. Tampico Habanero", precio:269, descripcion:"Tampico Picante, Cangrejo y Queso." },
      { nombre:"Sushi Avocado Teriyaki",     precio:269, descripcion:"Pollo Crunchy, Aguacate y Zanahoria." },
      { nombre:"Sushi Spicy Tuna",           precio:279, descripcion:"Atún Picante con Teriyaki." },
      { nombre:"Sushi Mr. Tempura",          precio:289, descripcion:"Manchego Capeado, Cangrejo y Chipotle." },
      { nombre:"Sushi Blue Cheese",          precio:269, descripcion:"Arrachera, Queso Azul y Costra Crujiente." },
      { nombre:"Sushi Hot Mango",            precio:215, descripcion:"Kanikama, Mango y Chile Serrano." },
    ],
    "Combos": [
      { nombre:"Combo Mr. 4x4",   precio:217, descripcion:"4 Medios Rollos a elegir. $199 los martes." },
      { nombre:"Combo Lunch Box", precio:197, descripcion:"Entrada + Arroz + Rollo + Agua a elegir. Lun–Jue." },
    ],
    "Sushi Box": [
      { nombre:"Sushi Box Clásico",   precio:750, descripcion:"6 Rollos en Charola para compartir." },
      { nombre:"Sushi Box Light",     precio:580, descripcion:"4 Rollos y 2 Entradas. Incluye edamames." },
      { nombre:"Sushi Box Tropical",  precio:825, descripcion:"6 Rollos especiales." },
      { nombre:"Sushi Box Tuna Sake", precio:950, descripcion:"4 Rollos y 8 Nigiris de atún y salmón." },
      { nombre:"Entrada Box",         precio:699, descripcion:"5 Entradas en Charola." },
    ],
    "Entradas": [
      { nombre:"Edamames Asados",               precio:110, descripcion:"Vainas de soya asadas con sal de mar." },
      { nombre:"Edamames Spicy",                precio:169, descripcion:"Vainas de soya asadas con salsa spicy." },
      { nombre:"Chiles Tempura",                precio:155, descripcion:"Jalapeños rellenos de queso crema y kanikama." },
      { nombre:"Dumplings de Vegetales",        precio:137, descripcion:"Ravioles al vapor rellenos de vegetales." },
      { nombre:"Dumplings de Vegetales Fritos", precio:137, descripcion:"Ravioles fritos rellenos de vegetales." },
      { nombre:"Dumplings de Cerdo",            precio:137, descripcion:"Ravioles al vapor rellenos de cerdo." },
      { nombre:"Dumplings de Cerdo Fritos",     precio:137, descripcion:"Ravioles fritos rellenos de cerdo." },
    ],
    "Hand Rolls": [
      { nombre:"Tampico Especial Hand Roll", precio:107, descripcion:"Cangrejo, Aguacate y Masago." },
      { nombre:"Kai Hand Roll Salmón",       precio:107, descripcion:"Salmón con Salsa BBQ." },
      { nombre:"Kai Hand Roll Atún",         precio:107, descripcion:"Atún con Salsa BBQ." },
      { nombre:"Diavolo Hand Roll",          precio:107, descripcion:"Camarón Tempura y Salsa Diablo." },
    ],
    "Sopas": [
      { nombre:"Sopa Miso",        precio:85,  descripcion:"Tofu y Cebollín en Caldo de Miso." },
      { nombre:"Sopa T-Udon",      precio:149, descripcion:"Camarón y Verduras Tempurizadas." },
      { nombre:"Sopa Coco Ramen",  precio:235, descripcion:"Pollo, Huevo y Verduras en Caldo de Coco." },
      { nombre:"Sopa Ramen Bacon", precio:245, descripcion:"Panceta Ahumada, Huevo y Espinaca." },
      { nombre:"Sopa Ramen Curry", precio:235, descripcion:"Pollo, Manzana y Espinaca con Curry." },
    ],
    "Brochetas Kushiagues": [
      { nombre:"Kushiague de Queso",    precio:185, descripcion:"3 brochetas rellenas de queso fundido." },
      { nombre:"Kushiague de Plátano",  precio:159, descripcion:"3 brochetas de queso y plátano." },
      { nombre:"Kushiague de Camarón",  precio:215, descripcion:"3 brochetas de camarón y queso." },
      { nombre:"Kushiague de Cangrejo", precio:210, descripcion:"3 brochetas de queso y kani." },
      { nombre:"Combo Kushiague",       precio:289, descripcion:"6 brochetas mixtas." },
    ],
    "Ensaladas": [
      { nombre:"Ensalada Tuna Yuzu",   precio:269, descripcion:"Atún Sellado, Aguacate y Vinagreta Soya." },
      { nombre:"Ensalada Mango Salad", precio:219, descripcion:"Salmón, Mango y Salsa de Miel." },
    ],
    "Arroz": [
      { nombre:"Yakimeshi Camarón",   precio:150, descripcion:"Arroz salteado con camarones." },
      { nombre:"Yakimeshi Mixto",     precio:154, descripcion:"Arroz salteado con pollo, res y camarones." },
      { nombre:"Yakimeshi Arrachera", precio:145, descripcion:"Arroz salteado con arrachera." },
      { nombre:"Yakimeshi Verduras",  precio:97,  descripcion:"Arroz salteado vegetariano." },
      { nombre:"Arroz Gohan",         precio:69,  descripcion:"Arroz japonés al vapor." },
      { nombre:"Arroz Chaufa",        precio:137, descripcion:"Pollo, Camarón y Pimientos estilo asiático." },
    ],
    "Rollos Tradicionales": [
      { nombre:"Sushi Tuna Maki",               precio:207, descripcion:"Atún Clásico con Queso." },
      { nombre:"Sushi Unagui Maki",             precio:315, descripcion:"Anguila Glaseada Clásica." },
      { nombre:"Sushi Ebi Maki",                precio:215, descripcion:"Camarón y Queso Tradicional." },
      { nombre:"Sushi Kani Maki",               precio:215, descripcion:"Cangrejo con Queso Tradicional." },
      { nombre:"Sushi Queso Maki Atún",         precio:167, descripcion:"Envuelto en Queso con Atún." },
      { nombre:"Sushi Queso Maki Camarón",      precio:167, descripcion:"Envuelto en Queso con Camarón." },
      { nombre:"Sushi Queso Maki Salmón",       precio:167, descripcion:"Envuelto en Queso con Salmón." },
      { nombre:"Sushi California Maki Atún",    precio:155, descripcion:"Atún Fresco con Ajonjolí." },
      { nombre:"Sushi California Maki Salmón",  precio:155, descripcion:"Salmón Fresco con Ajonjolí." },
      { nombre:"Sushi California Maki Camarón", precio:155, descripcion:"Camarón Fresco con Ajonjolí." },
      { nombre:"Sushi Filadelfia Maki Atún",    precio:147, descripcion:"Atún y Queso con Alga." },
      { nombre:"Sushi Filadelfia Maki Camarón", precio:147, descripcion:"Camarón y Queso con Alga." },
      { nombre:"Sushi Filadelfia Maki Salmón",  precio:147, descripcion:"Salmón y Queso con Alga." },
      { nombre:"Sushi Avocado Maki Atún",       precio:165, descripcion:"Atún con Queso y Aguacate." },
      { nombre:"Sushi Avocado Maki Camarón",    precio:165, descripcion:"Camarón con Queso y Aguacate." },
      { nombre:"Sushi Avocado Maki Salmón",     precio:165, descripcion:"Salmón con Queso y Aguacate." },
    ],
    "Rollos Especialidades": [
      { nombre:"Sushi Spicy Tuna",           precio:210, descripcion:"Atún Picante con Teriyaki." },
      { nombre:"Sushi Garlic Tuna",          precio:225, descripcion:"Atún, Ajo, Limón y Camarón Tempura." },
      { nombre:"Sushi Mr. Tampico Habanero", precio:177, descripcion:"Picante con Cangrejo y Queso." },
      { nombre:"Sushi Mr. Dragon",           precio:220, descripcion:"Mango, Shichimi y Camarón Crunchy." },
      { nombre:"Sushi Mr. Tempura",          precio:199, descripcion:"Manchego Capeado, Cangrejo y Chipotle." },
      { nombre:"Sushi Mr. Kakiage",          precio:220, descripcion:"Verduras Tempura, Cangrejo y Queso." },
      { nombre:"Sushi Red Dragon",           precio:225, descripcion:"Atún, Chipotle y Tempura Crunch." },
      { nombre:"Sushi Mr. Tampico",          precio:177, descripcion:"Cangrejo, Tampico y Queso Crema." },
      { nombre:"Sushi Mr. Ebi",              precio:210, descripcion:"Camarón Empanizado, Chipotle y Queso." },
      { nombre:"Sushi Queso Maki Fry",       precio:195, descripcion:"Camarón Crunchy, Queso y Tampico." },
      { nombre:"Sushi Mr. Keko",             precio:237, descripcion:"Salmón, Queso Crema, Aguacate y Pepino." },
      { nombre:"Sushi Mr. Tam Beef",         precio:230, descripcion:"Res, Aguacate, Tampico y Queso Crema." },
      { nombre:"Sushi Avocado Teriyaki",     precio:197, descripcion:"Pollo Crunchy, Aguacate y Zanahoria." },
      { nombre:"Sushi Mr. Mango",            precio:195, descripcion:"Mango, Cangrejo, Queso Crema y Aguacate." },
      { nombre:"Sushi Baby Maki",            precio:187, descripcion:"Baby Squid, Salsa Tare y Queso Crema." },
      { nombre:"Sushi Mr. Diablo",           precio:337, descripcion:"Salmón Fresco, Camarón Crunchy y Queso." },
      { nombre:"Sushi Piña Spicy",           precio:175, descripcion:"Camarón Tempura, Piña Picante y Queso." },
      { nombre:"Mr. Manchego",               precio:195, descripcion:"Queso Manchego Crunchy, Cangrejo y Aguacate." },
      { nombre:"Sushi Avocado Habanero",     precio:197, descripcion:"Tampico Picante, Camarón y Kakiage." },
      { nombre:"Sushi Tsunami",              precio:185, descripcion:"Salmón, Aguacate, Cangrejo y Tampico." },
      { nombre:"Sushi Tunagui",              precio:197, descripcion:"Atún, Anguila, Masago y Aguacate." },
      { nombre:"Sushi Tuna King",            precio:225, descripcion:"Atún Picante, Aguacate y Chile Tempura." },
      { nombre:"Sushi Tempura Maki",         precio:197, descripcion:"Queso Crema, Tempura, Cangrejo y Chile." },
    ],
    "Bowls": [
      { nombre:"Bowl Yakimeshi Rib Eye", precio:210, descripcion:"Rib Eye, Brócoli y Salsa Ajonjolí." },
      { nombre:"Bowl Gohan Mr. Sushi",   precio:207, descripcion:"Cangrejo, Aguacate y Tampico." },
      { nombre:"Bowl Gohan To Banjan",   precio:175, descripcion:"Pollo, Brócoli y Salsa Jengibre." },
      { nombre:"Bowl Gohan Teriyaki",    precio:159, descripcion:"Pollo Teriyaki y Arroz al Vapor." },
      { nombre:"Bowl Chicken Teriyaki",  precio:215, descripcion:"Pollo, Brócoli y Pasta Udon." },
      { nombre:"Bowl Tuna Rayu",         precio:207, descripcion:"Atún Rayu, Aguacate y Ajonjolí." },
      { nombre:"Bowl Tokyo",             precio:207, descripcion:"Camarón Crunchy, Mango y Queso Crema." },
      { nombre:"Bowl Sake Wake",         precio:237, descripcion:"Salmón Asado, Aguacate y Edamames." },
      { nombre:"Bowl Kin Roca",          precio:207, descripcion:"Salmón Roca, Mango, Aguacate y Edamames." },
    ],
    "Cocina Caliente": [
      { nombre:"Kani Tori",      precio:190, descripcion:"Pollo Empanizado, Kanikama y Salsa Chipotle." },
      { nombre:"Roast Tuna",     precio:275, descripcion:"Atún Sellado, Soya Dulce y Salsa Tártara." },
      { nombre:"Teriyaki Pollo", precio:320, descripcion:"Pollo en Salsa Teriyaki con Verduras." },
    ],
    "Postres": [
      { nombre:"Camelado",                    precio:120, descripcion:"Gelatina de Café, Helado de Vainilla y Kahlúa." },
      { nombre:"Tempura Helado Chocolate",    precio:140, descripcion:"Helado Frito de Vainilla con Chocolate." },
      { nombre:"Tempura Helado Frutos Rojos", precio:140, descripcion:"Helado Frito con Mermelada de Berries." },
    ],
    "Bebidas": [
      { nombre:"Coca Cola",            precio:67, descripcion:"Refresco Coca Cola" },
      { nombre:"Coca Cola Light",      precio:67, descripcion:"Refresco Coca Cola Light" },
      { nombre:"Coca Cola Sin Azúcar", precio:67, descripcion:"Refresco Coca Cola sin azúcar" },
      { nombre:"Sprite",               precio:67, descripcion:"Refresco Sprite" },
      { nombre:"Sidral",               precio:67, descripcion:"Refresco Sidral" },
      { nombre:"Agua Embotellada",     precio:67, descripcion:"Agua natural embotellada" },
    ],
  },

  politicas: {
    reservaciones: "Con mínimo 2 horas de anticipación. Máximo 20 personas por reservación.",
    cancelaciones: "Cancelaciones sin cargo hasta 1 hora antes.",
    delivery: "Envío gratis a cualquier dirección. Sin restricciones de zona.",
    tiempo_espera_pedido: "30–40 minutos en hora pico.",
    tiempo_domicilio: "40 minutos aproximadamente.",
  },
};
